from __future__ import annotations


BAYESIAN_TABLES = {
    "level_network_eras",
    "level_outreach_targets",
    "level_outreach_opportunities",
    "bayes_model_versions",
    "bayes_model_snapshots",
    "bayes_predictions",
    "bayes_capacity_forecasts",
    "bayes_model_exclusions",
    "bayes_model_controls",
    "level_notification_subscriptions",
    "level_notification_events",
    "level_notification_deliveries",
    "level_request_duplicate_occurrences",
}


BAYESIAN_SCHEMA = (
    """CREATE TABLE IF NOT EXISTS level_network_eras(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        started_ts INTEGER NOT NULL,
        started_by INTEGER NOT NULL,
        ended_ts INTEGER,
        ended_by INTEGER,
        prior_mode TEXT NOT NULL DEFAULT 'discounted_previous',
        carryover_effective_n REAL NOT NULL DEFAULT 4,
        prior_alpha REAL NOT NULL DEFAULT 1,
        prior_beta REAL NOT NULL DEFAULT 1,
        public_reason TEXT NOT NULL DEFAULT '',
        private_reason TEXT NOT NULL DEFAULT '',
        notes TEXT NOT NULL DEFAULT '',
        correlation_id TEXT NOT NULL UNIQUE
    );""",
    """CREATE TABLE IF NOT EXISTS level_outreach_targets(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        private_target_key TEXT NOT NULL,
        private_label TEXT NOT NULL DEFAULT '',
        created_ts INTEGER NOT NULL,
        last_seen_ts INTEGER NOT NULL,
        UNIQUE(guild_id,private_target_key)
    );""",
    """CREATE TABLE IF NOT EXISTS level_outreach_opportunities(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        network_era_id INTEGER NOT NULL,
        cycle_id INTEGER,
        episode_id INTEGER NOT NULL,
        queue_id INTEGER NOT NULL,
        level_id TEXT NOT NULL,
        target_id INTEGER,
        private_target_key TEXT NOT NULL,
        private_target_label TEXT NOT NULL DEFAULT '',
        initial_route TEXT NOT NULL DEFAULT 'other',
        current_route TEXT NOT NULL DEFAULT 'other',
        route_type TEXT NOT NULL,
        first_planned_ts INTEGER,
        first_attempt_ts INTEGER,
        last_attempt_ts INTEGER,
        confirmed_submission_ts INTEGER,
        closed_ts INTEGER,
        follow_up_count INTEGER NOT NULL DEFAULT 0,
        outcome TEXT NOT NULL DEFAULT 'pending',
        outcome_ts INTEGER,
        failure_reason TEXT,
        actor_id INTEGER,
        dependency_group TEXT,
        exclusion_reason TEXT,
        source_attempt_id INTEGER NOT NULL,
        updated_ts INTEGER NOT NULL,
        UNIQUE(episode_id,queue_id,private_target_key)
    );""",
    """CREATE TABLE IF NOT EXISTS bayes_model_versions(
        model_key TEXT NOT NULL,
        version TEXT NOT NULL,
        config_json TEXT NOT NULL,
        created_ts INTEGER NOT NULL,
        PRIMARY KEY(model_key,version)
    );""",
    """CREATE TABLE IF NOT EXISTS bayes_model_snapshots(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        network_era_id INTEGER NOT NULL,
        model_key TEXT NOT NULL,
        model_version TEXT NOT NULL,
        subgroup_key TEXT NOT NULL DEFAULT 'global',
        status TEXT NOT NULL,
        alpha REAL NOT NULL,
        beta REAL NOT NULL,
        observations INTEGER NOT NULL,
        successes INTEGER NOT NULL,
        failures INTEGER NOT NULL,
        posterior_mean REAL NOT NULL,
        intervals_json TEXT NOT NULL,
        evidence_strength TEXT NOT NULL,
        freshness_ts INTEGER,
        calibration_json TEXT NOT NULL DEFAULT '{}',
        reason TEXT NOT NULL DEFAULT '',
        prior_alpha REAL,
        prior_beta REAL,
        data_cutoff_ts INTEGER,
        config_hash TEXT,
        generated_ts INTEGER NOT NULL,
        UNIQUE(guild_id,network_era_id,model_key,model_version,subgroup_key,generated_ts)
    );""",
    """CREATE TABLE IF NOT EXISTS bayes_predictions(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        network_era_id INTEGER NOT NULL,
        model_key TEXT NOT NULL,
        model_version TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        subgroup_key TEXT NOT NULL DEFAULT 'global',
        probability REAL NOT NULL,
        median REAL,
        posterior_alpha REAL,
        posterior_beta REAL,
        intervals_json TEXT NOT NULL DEFAULT '{}',
        data_cutoff_ts INTEGER,
        status TEXT NOT NULL,
        evidence_strength TEXT NOT NULL,
        predicted_ts INTEGER NOT NULL,
        resolved_outcome INTEGER,
        resolved_ts INTEGER,
        brier_score REAL,
        metadata_json TEXT NOT NULL DEFAULT '{}',
        access_prediction_id INTEGER,
        rating_prediction_id INTEGER,
        access_snapshot_id INTEGER,
        rating_snapshot_id INTEGER,
        UNIQUE(model_key,model_version,entity_type,entity_id,predicted_ts)
    );""",
    """CREATE TABLE IF NOT EXISTS bayes_capacity_forecasts(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        network_era_id INTEGER NOT NULL,
        cycle_id INTEGER,
        model_version TEXT NOT NULL,
        queue_size INTEGER NOT NULL,
        expected_successes REAL NOT NULL,
        k80 INTEGER NOT NULL,
        k90 INTEGER NOT NULL,
        k95 INTEGER NOT NULL,
        draws INTEGER NOT NULL,
        seed INTEGER NOT NULL,
        input_json TEXT NOT NULL,
        actual_submissions INTEGER,
        resolved_ts INTEGER,
        generated_ts INTEGER NOT NULL
    );""",
    """CREATE TABLE IF NOT EXISTS bayes_model_exclusions(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        model_key TEXT NOT NULL DEFAULT 'all',
        reason_code TEXT NOT NULL,
        detail TEXT NOT NULL DEFAULT '',
        active INTEGER NOT NULL DEFAULT 1,
        created_by INTEGER NOT NULL,
        created_ts INTEGER NOT NULL,
        revoked_by INTEGER,
        revoked_ts INTEGER
    );""",
    """CREATE UNIQUE INDEX IF NOT EXISTS idx_bayes_model_exclusions_active
       ON bayes_model_exclusions(guild_id,entity_type,entity_id,model_key)
       WHERE active=1;""",
    """CREATE TABLE IF NOT EXISTS bayes_model_controls(
        guild_id INTEGER NOT NULL,
        model_key TEXT NOT NULL,
        publication_paused INTEGER NOT NULL DEFAULT 0,
        pause_reason TEXT NOT NULL DEFAULT '',
        updated_by INTEGER,
        updated_ts INTEGER NOT NULL,
        PRIMARY KEY(guild_id,model_key)
    );""",
    """CREATE TABLE IF NOT EXISTS level_notification_subscriptions(
        guild_id INTEGER NOT NULL,
        level_id TEXT NOT NULL,
        user_id INTEGER NOT NULL,
        source TEXT NOT NULL DEFAULT 'manual',
        major_updates INTEGER NOT NULL DEFAULT 1,
        priority_band_changes INTEGER NOT NULL DEFAULT 0,
        final_outcome INTEGER NOT NULL DEFAULT 1,
        active INTEGER NOT NULL DEFAULT 1,
        created_ts INTEGER NOT NULL,
        updated_ts INTEGER NOT NULL,
        PRIMARY KEY(guild_id,level_id,user_id)
    );""",
    """CREATE TABLE IF NOT EXISTS level_notification_events(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        level_id TEXT NOT NULL,
        queue_id INTEGER,
        episode_id INTEGER,
        event_type TEXT NOT NULL,
        event_key TEXT NOT NULL UNIQUE,
        payload_json TEXT NOT NULL DEFAULT '{}',
        created_ts INTEGER NOT NULL
    );""",
    """CREATE TABLE IF NOT EXISTS level_notification_deliveries(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        event_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        outbox_id INTEGER,
        status TEXT NOT NULL DEFAULT 'queued',
        delivered_message_id INTEGER,
        failure_reason TEXT,
        created_ts INTEGER NOT NULL,
        updated_ts INTEGER NOT NULL,
        UNIQUE(event_id,user_id)
    );""",
    """CREATE TABLE IF NOT EXISTS level_request_duplicate_occurrences(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        guild_id INTEGER NOT NULL,
        level_id TEXT NOT NULL,
        user_id INTEGER NOT NULL,
        queue_id INTEGER NOT NULL,
        wave_id INTEGER,
        created_ts INTEGER NOT NULL,
        correlation_id TEXT NOT NULL
    );""",
    """CREATE UNIQUE INDEX IF NOT EXISTS idx_network_era_active
        ON level_network_eras(guild_id) WHERE status='active';""",
    """CREATE INDEX IF NOT EXISTS idx_opportunities_model
        ON level_outreach_opportunities(guild_id,network_era_id,outcome,route_type);""",
    """CREATE INDEX IF NOT EXISTS idx_outreach_targets_private
        ON level_outreach_targets(guild_id,private_target_key);""",
    """CREATE INDEX IF NOT EXISTS idx_model_snapshots_latest
        ON bayes_model_snapshots(guild_id,model_key,network_era_id,generated_ts DESC);""",
    """CREATE INDEX IF NOT EXISTS idx_predictions_calibration
        ON bayes_predictions(guild_id,model_key,resolved_ts,predicted_ts);""",
    """CREATE INDEX IF NOT EXISTS idx_capacity_latest
        ON bayes_capacity_forecasts(guild_id,generated_ts DESC);""",
    """CREATE INDEX IF NOT EXISTS idx_level_subscriptions_user
        ON level_notification_subscriptions(guild_id,user_id,active);""",
    """CREATE INDEX IF NOT EXISTS idx_level_notification_delivery
        ON level_notification_deliveries(status,updated_ts);""",
    """CREATE INDEX IF NOT EXISTS idx_duplicate_occurrences_level
        ON level_request_duplicate_occurrences(guild_id,level_id,created_ts DESC);""",
)
